### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by BlindDevIE** [svprdga/Text-Recognition-Flutter#1]
Hello.
First, thank you so much for your tutorial.

Do you know why this code do not work on Android 13? I ran it in a device with Android 12 and bellow.

**Comment by svprdga** [comment]
> First, thank you so much for your tutorial.

You're welcome!

> Do you know why this code do not work on Android 13? I ran it in a device with Android 12 and bellow.

Yes. It's because of [this issue](https://github.com/flutter/flutter/issues/109769) in the camera plugin. I've downgraded the target SDK version to 32, now it works.

**Comment by MaetrixG** [comment]
Hi! I'm new to app development and when I tried running your code I received this output:

A problem occurred configuring root project 'android'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file

What does this mean and what can I do to make it work?

**Comment by svprdga** [comment]
Hello @MaetrixG, can you give me more details?

For example, how are you trying to run the project? Can you write the output of running `flutter doctor` here?
